---
- name: Check system architecture is supported
  fail:
    msg: "{{ ansible_architecture }} is not a supported architecture"
  when: docker_deb_architecture[ansible_architecture] is not defined

- name: Install Docker repository key
  get_url:
    url: "{{ docker_repository_key_url }}"
    dest: "{{ docker_repository_key_path }}"
    checksum: "{{ docker_repository_key_checksum | d(omit) }}"
    mode: "0644"

- name: Remove Docker repository key from /etc/apt/trusted.gpg.d
  file:
    path: /etc/apt/trusted.gpg.d/docker.gpg
    state: absent

- name: Remove Docker repository without signed-by
  apt_repository:
    repo: >-
      deb [arch={{ docker_deb_architecture[ansible_architecture] }}]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      {{ docker_release_channel }}
    filename: docker
    state: absent

- name: Add Docker repository
  apt_repository:
    repo: >-
        deb [arch={{ docker_deb_architecture[ansible_architecture] }} signed-by={{ docker_repository_key_path }}]
        https://download.docker.com/linux/{{ ansible_distribution | lower }}
        {{ ansible_distribution_release }}
        {{ docker_release_channel }}
    filename: docker
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create /etc/docker directory
  file:
    path: "/etc/docker"
    state: directory
    mode: "0755"

- name: Install Docker daemon configuration
  template:
    src: etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0644"
    backup: "{{ docker_daemon_config_backup }}"
  vars:
    _docker_daemon_config: >-
      {{
        docker_daemon_config |
        combine(docker_group_daemon_config, docker_host_daemon_config, recursive=True) |
        to_nice_json
      }}
  notify: restart docker

- name: Enable and start Docker
  service:
    name: docker
    enabled: "{{ docker_service_enabled }}"
    state: "{{ docker_service_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
