---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      stat:
        path: "/usr/bin/docker"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Read Docker daemon configuration file
      slurp:
        path: "/etc/docker/daemon.json"
      register: _docker_daemon_config

    - name: Ensure Docker daemon configuration is correct
      fail:
        msg: Docker configuration doesn't match expected value
      when: _config != _expected
      vars:
        _config: "{{ _docker_daemon_config.content | b64decode | from_json }}"
        # recursively merged contents of docker_daemon_config,
        # docker_group_daemon_config and docker_host_daemon_config
        _expected:
          iptables: true
          live-restore: false
          log-driver: json-file
          log-opts:
            max-file: "4"
            max-size: "250m"
