---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.stat:
        path: "/usr/bin/docker"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure specified Docker version is installed
      ansible.builtin.command: dpkg-query -f '${Version}' -W docker-ce
      register: result
      changed_when: false
      failed_when: >-
        result.rc != 0 or
        result.stdout is not match(docker_package_version)

    - name: Ensure specified containerd version is installed
      ansible.builtin.command: dpkg-query -f '${Version}' -W containerd.io
      register: result
      changed_when: false
      failed_when: >-
        result.rc != 0 or
        result.stdout is not match("1\.6\.24")

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: Docker
        state: started
      register: result
      check_mode: true
      failed_when: result is changed

    - name: Ensure Docker daemon configuration is correct
      ansible.builtin.copy:
        content: |
          {
              "iptables": true,
              "live-restore": false,
              "log-driver": "json-file",
              "log-opts": {
                  "max-file": "4",
                  "max-size": "250m"
              }
          }
        dest: "/etc/docker/daemon.json"
        mode: "0644"
      register: result
      failed_when: result is changed
