---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Docker is installed
      stat:
        path: "/usr/bin/docker"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure Docker is running
      service:
        name: Docker
        state: started
      register: result
      check_mode: true
      failed_when: result is changed

    - name: Ensure Docker daemon configuration is correct
      copy:
        content: |
          {
              "iptables": true,
              "live-restore": false,
              "log-driver": "json-file",
              "log-opts": {
                  "max-file": "4",
                  "max-size": "250m"
              }
          }
        dest: "/etc/docker/daemon.json"
        mode: "0644"
      register: result
      failed_when: result is changed
